### ISSUE TITLE
Summarization tranning notebook gives a result of zero.

### ISSUE THREAD

**Issue by miguelwon** [AlaFalaki/tutorial_notebooks#1]
Hi,
I just ran your summarization tranning [notebook](https://github.com/NLPiation/tutorial_notebooks/blob/main/summarization/hf_BERT-BERT_training.ipynb) and is giving me neatly zero results for rouge score.

**Comment by NLPiation** [comment]
Hi @miguelwon,
To be clear, it is not my code. It's been taken from [Huggingface](https://huggingface.co/patrickvonplaten/bert2bert_cnn_daily_mail) hub.

Regarding your question, there are a number of changes you have to make to get good results. The variables like encoder max length, batch size, and the number of epochs. It is really hard to train BART on the Google Colab and get good results. The code you mention is just going through the concept and implementation as an example.

**Comment by miguelwon** [comment]
Thanks for the comment. I have spend now some time with this and I think is related with the transformers version. It works fine with `4.2.1` (as indicated in the notebook) but not working with the latest.
